import io
from datetime import datetime
import xml.sax.saxutils as saxutils
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT

def safe_escape(text):
    if text is None:
        return "Unavailable"
    text_str = str(text)
    # ReportLab Paragraphs parse <, >, & as XML tags unless escaped.
    return saxutils.escape(text_str)

def format_currency(value):
    if value is None:
        return "Unavailable"
    try:
        val = float(value)
        if abs(val) >= 1e9:
            return f"${val / 1e9:.2f}B"
        elif abs(val) >= 1e6:
            return f"${val / 1e6:.2f}M"
        else:
            return f"${val:,.2f}"
    except (ValueError, TypeError):
        return safe_escape(value)

def format_number(value, is_percentage=False):
    if value is None:
        return "Unavailable"
    try:
        val = float(value)
        if is_percentage:
            return f"{val:.2f}%"
        return f"{val:,.2f}"
    except (ValueError, TypeError):
        return safe_escape(value)

def create_header_footer(canvas, doc, company, ticker, date_str):
    canvas.saveState()
    # Header
    canvas.setFont('Helvetica-Bold', 10)
    canvas.drawString(inch, A4[1] - 0.5 * inch, "Alpha Terminal")
    canvas.setFont('Helvetica', 10)
    canvas.drawRightString(A4[0] - inch, A4[1] - 0.5 * inch, "AI Investment Research Report")
    
    # Footer
    canvas.setFont('Helvetica', 8)
    canvas.drawString(inch, 0.5 * inch, f"Generated by Alpha Terminal | {date_str}")
    canvas.drawRightString(A4[0] - inch, 0.5 * inch, f"Page {doc.page}")
    
    # Disclaimer
    canvas.setFont('Helvetica-Oblique', 7)
    canvas.drawCentredString(A4[0] / 2.0, 0.3 * inch, "This report is for informational and research purposes only and does not constitute personalized investment advice.")
    canvas.restoreState()

def generate_research_pdf(report_input) -> bytes:
    buffer = io.BytesIO()
    
    # Normalize input: it might be an InvestmentResearchReport model or a dict.
    if hasattr(report_input, "model_dump"):
        report_data = report_input.model_dump(mode="json")
    elif isinstance(report_input, str):
        import json
        try:
            report_data = json.loads(report_input)
        except Exception:
            report_data = {}
    else:
        report_data = dict(report_input) if report_input else {}
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        spaceAfter=6,
        textColor=colors.HexColor('#1a1a1a')
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        spaceAfter=24,
        textColor=colors.HexColor('#666666')
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        spaceBefore=16,
        spaceAfter=8,
        textColor=colors.HexColor('#2c3e50')
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        spaceAfter=8,
        alignment=TA_LEFT
    )

    company = safe_escape(report_data.get('company', 'Unknown Company'))
    ticker = safe_escape(report_data.get('ticker', 'UNKNOWN'))
    date_str = safe_escape(report_data.get('research_date', datetime.now().strftime("%Y-%m-%d")))
    
    inv_strat = report_data.get('investment_strategy', {})
    mkt_snap = report_data.get('market_snapshot', {})
    fin_sum = report_data.get('financial_summary', {})
    fin_mets = report_data.get('financial_metrics', {})
    data_sources = report_data.get('data_sources', {})
    
    elements = []
    
    # HEADER SECTION
    elements.append(Paragraph(f"{company} ({ticker})", title_style))
    elements.append(Paragraph(f"Research Date: {date_str}", subtitle_style))
    
    # EXECUTIVE SUMMARY
    elements.append(Paragraph("EXECUTIVE SUMMARY", heading_style))
    rec = safe_escape(inv_strat.get("recommendation", "Unavailable"))
    conf = safe_escape(inv_strat.get("confidence", "Unavailable"))
    elements.append(Paragraph(f"<b>Recommendation:</b> {rec} | <b>Confidence:</b> {conf}", body_style))
    
    if inv_strat.get("investment_thesis"):
        elements.append(Paragraph("<b>Investment Thesis:</b>", body_style))
        elements.append(Paragraph(safe_escape(inv_strat.get("investment_thesis")), body_style))
        
    # COMPANY & BUSINESS ASSESSMENT
    elements.append(Paragraph("COMPANY & BUSINESS ASSESSMENT", heading_style))
    if inv_strat.get("company_quality"):
        elements.append(Paragraph("<b>Company Quality:</b>", body_style))
        elements.append(Paragraph(safe_escape(inv_strat.get("company_quality")), body_style))
    if inv_strat.get("fundamental_assessment"):
        elements.append(Paragraph("<b>Fundamental Assessment:</b>", body_style))
        elements.append(Paragraph(safe_escape(inv_strat.get("fundamental_assessment")), body_style))
    if inv_strat.get("market_and_news_assessment"):
        elements.append(Paragraph("<b>Market & News Assessment:</b>", body_style))
        elements.append(Paragraph(safe_escape(inv_strat.get("market_and_news_assessment")), body_style))
        
    # VALUATION
    elements.append(Paragraph("VALUATION", heading_style))
    if inv_strat.get("valuation_view"):
        elements.append(Paragraph("<b>Valuation View:</b>", body_style))
        elements.append(Paragraph(safe_escape(inv_strat.get("valuation_view")), body_style))
    if inv_strat.get("valuation_assessment"):
        elements.append(Paragraph("<b>Valuation Assessment:</b>", body_style))
        elements.append(Paragraph(safe_escape(inv_strat.get("valuation_assessment")), body_style))
        
    # Market Metrics Table
    elements.append(Paragraph("<b>Market Metrics:</b>", body_style))
    val_data = [
        ["Metric", "Value"],
        ["Market Capitalization", format_currency(mkt_snap.get("market_cap"))],
        ["Current Price", format_currency(mkt_snap.get("current_price"))],
        ["52 Week High", format_currency(mkt_snap.get("week_52_high"))],
        ["52 Week Low", format_currency(mkt_snap.get("week_52_low"))],
        ["Beta", format_number(mkt_snap.get("beta"))],
        ["Dividend Yield", format_number(mkt_snap.get("dividend_yield"), is_percentage=True)]
    ]
    
    val_table = Table(val_data, colWidths=[3*inch, 3*inch])
    val_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f3f4f6')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#111827')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
    ]))
    elements.append(val_table)
    elements.append(Spacer(1, 0.2*inch))
    
    # FINANCIAL SUMMARY
    elements.append(Paragraph("FINANCIAL SUMMARY", heading_style))
    fin_data = [
        ["Metric", "Value"],
        ["Revenue", format_currency(fin_sum.get("revenue"))],
        ["Gross Profit", format_currency(fin_sum.get("gross_profit"))],
        ["Operating Income", format_currency(fin_sum.get("operating_income"))],
        ["Net Income", format_currency(fin_sum.get("net_income"))],
        ["Operating Cash Flow", format_currency(fin_sum.get("operating_cash_flow"))],
        ["Free Cash Flow", format_currency(fin_mets.get("free_cash_flow"))],
    ]
    fin_table = Table(fin_data, colWidths=[3*inch, 3*inch])
    fin_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f3f4f6')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#111827')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('LINEBELOW', (0, 0), (-1, -1), 0.5, colors.HexColor('#e5e7eb')),
    ]))
    elements.append(fin_table)
    elements.append(Spacer(1, 0.2*inch))

    # RISK ANALYSIS
    elements.append(Paragraph("RISK ANALYSIS", heading_style))
    if inv_strat.get("risk_assessment"):
        elements.append(Paragraph("<b>Risk Assessment:</b>", body_style))
        elements.append(Paragraph(safe_escape(inv_strat.get("risk_assessment")), body_style))
        
    key_risks = inv_strat.get("key_risks", [])
    if key_risks and isinstance(key_risks, list):
        elements.append(Paragraph("<b>Key Risks:</b>", body_style))
        for risk in key_risks:
            elements.append(Paragraph(f"• {safe_escape(risk)}", body_style))
            
    # SCENARIOS
    elements.append(Paragraph("SCENARIOS", heading_style))
    if inv_strat.get("bull_case"):
        elements.append(Paragraph("<b>Bull Case:</b>", body_style))
        elements.append(Paragraph(safe_escape(inv_strat.get("bull_case")), body_style))
    if inv_strat.get("base_case"):
        elements.append(Paragraph("<b>Base Case:</b>", body_style))
        elements.append(Paragraph(safe_escape(inv_strat.get("base_case")), body_style))
    if inv_strat.get("bear_case"):
        elements.append(Paragraph("<b>Bear Case:</b>", body_style))
        elements.append(Paragraph(safe_escape(inv_strat.get("bear_case")), body_style))
        
    # KEY ITEMS
    key_items_elements = []
    key_items_elements.append(Paragraph("KEY ITEMS", heading_style))
    key_catalysts = inv_strat.get("key_catalysts", [])
    if key_catalysts and isinstance(key_catalysts, list):
        key_items_elements.append(Paragraph("<b>Key Catalysts:</b>", body_style))
        for item in key_catalysts:
            key_items_elements.append(Paragraph(f"• {safe_escape(item)}", body_style))
            
    thesis_change_triggers = inv_strat.get("thesis_change_triggers", [])
    if thesis_change_triggers and isinstance(thesis_change_triggers, list):
        key_items_elements.append(Paragraph("<b>Thesis Change Triggers:</b>", body_style))
        for item in thesis_change_triggers:
            key_items_elements.append(Paragraph(f"• {safe_escape(item)}", body_style))
            
    elements.append(KeepTogether(key_items_elements))
            
    # DATA SOURCES
    elements.append(Paragraph("DATA SOURCES", heading_style))
    if isinstance(data_sources, dict):
        sources = [
            f"Market Data: {data_sources.get('market_data', 'Unknown')}",
            f"Financial Statements: {data_sources.get('financial_statements', 'Unknown')}",
            f"News: {data_sources.get('news', 'Unknown')}",
            f"Financial Metrics: {data_sources.get('metrics', 'Unknown')}",
            f"Specialist Analysis: {data_sources.get('specialist_analysis', 'Unknown')}",
            f"Investment Strategy: {data_sources.get('investment_strategy', 'Unknown')}"
        ]
        for src in sources:
            elements.append(Paragraph(f"• {safe_escape(src)}", body_style))

    # Build PDF
    def on_page(canvas, doc):
        create_header_footer(canvas, doc, company, ticker, date_str)

    doc.build(elements, onFirstPage=on_page, onLaterPages=on_page)
    
    return buffer.getvalue()
